alias czsh='vim $HOME/.zshrc'
alias szsh='source ~/.zshrc'
alias ls='exa'
alias l='ls -l'
alias la='ls -Hla --git'
alias lt='exa --tree --git --level=2 --long --group-directories-first --git-ignore --ignore-glob=__pycache__'
alias g='git'
alias apate='mosh apate -- tmux attach'
alias vim='nvim'
